import { StyleSheet } from 'react-native';
import { widthPercentageToDP as wp } from 'react-native-responsive-screen';

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 12,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: '#fff',
    borderBottomWidth: 1,
    borderColor: '#eee',
  },
  backBtn: {
    paddingVertical: 4,
    paddingHorizontal: 4,
    marginRight: 8,
    justifyContent: 'center',
    alignItems: 'center',
  },
  headerBtn: {
    padding: 4,
  },
  image: {
    width: wp('95%'),
    height: wp('55%'),
    borderRadius: 8,
    margin: 10,
    alignSelf: 'center',
    borderWidth: 2,
    borderColor: '#2196f3',
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginHorizontal: 12,
    marginVertical: 8,
  },
  icon: { fontSize: 16, marginRight: 8 },
  menuIcon: { fontSize: 20, marginLeft: 8 },
  authorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginHorizontal: 12,
    marginBottom: 8,
  },
  avatar: { width: 40, height: 40, borderRadius: 20, marginRight: 8 },
  author: { fontWeight: 'bold', fontSize: 16 },
  type: { color: '#888', fontSize: 12 },
  time: { color: '#888', fontSize: 12 },
  title: { fontSize: 22, fontWeight: 'bold', margin: 12 },
  card: {
    backgroundColor: '#f9f9f9',
    marginHorizontal: 12,
    marginBottom: 8,
    padding: 12,
    borderRadius: 8,
  },
  cardLarge: {
    backgroundColor: '#fff',
    marginHorizontal: 12,
    marginBottom: 8,
    padding: 24,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: '#eee',
    minHeight: 80,
    justifyContent: 'center',
  },
  cardTitle: { fontWeight: 'bold', marginBottom: 4, fontSize: 16 },
  cardDesc: { color: '#888', textAlign: 'center' },
  section: {
    fontSize: 16,
    fontWeight: 'bold',
    marginHorizontal: 12,
    marginBottom: 4,
  },
  videoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#f1f1f1',
    margin: 12,
    padding: 12,
    borderRadius: 8,
    justifyContent: 'center',
  },
  videoIcon: { fontSize: 24, marginRight: 8 },
  commentSection: { backgroundColor: '#fff', margin: 12, marginBottom: 24 },
  commentRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 4 },
  commentIcon: { fontSize: 18, marginRight: 4 },
  commentUser: { fontWeight: 'bold', marginRight: 4 },
  commentTime: { color: '#888', fontSize: 12, marginRight: 8 },
  commentText: { flex: 1 },
});

export default styles;