import { StyleSheet } from "react-native";

export const defaultPlaceholderColor = "#9f9e9eff";

export const styles = StyleSheet.create({
  header: { 
    fontSize: 22, 
    fontWeight: "700", 
    marginBottom: 24,
    color: "#ff6600" 
  },
  inputContainer: {
    marginBottom: 16,
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: "500",
    color: "#333333",
    marginBottom: 8,
  },
  required: {
    color: "#ff6600",
  },
  input: { 
    borderWidth: 1, 
    borderColor: "#e0e0e0", 
    borderRadius: 10, 
    padding: 12,
    backgroundColor: "#ffffff",
    fontSize: 16,
    color: "#333333",
  },
  charCount: {
    fontSize: 12,
    color: "#666666",
    textAlign: "right",
    marginTop: 4,
  },
  row: { 
    flexDirection: "row", 
    justifyContent: "space-between",
    marginVertical: 4
  },
  difficultyContainer: {
    flexDirection: 'row',
    gap: 16,
    marginTop: 8,
  },
  difficultyButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  difficultyButtonSelected: {
    backgroundColor: '#fff3e6',
    borderRadius: 8,
    paddingHorizontal: 6,
  },
  radioButton: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#e0e0e0',
    alignItems: 'center',
    justifyContent: 'center',
  },
  radioButtonInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#ff6600',
  },
  difficultyButtonText: {
    fontSize: 16,
    color: '#666666',
  },
  difficultyButtonTextSelected: {
    color: '#ff6600',
  },
  selectedItems: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginTop: 10,
    gap: 8,
  },
  selectedItem: {
    backgroundColor: '#fff3e6',
    paddingVertical: 8,
    paddingHorizontal: 12,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#ffd9b3',
    flexDirection: 'row',
    alignItems: 'center',
  },
  selectedItemText: {
    fontSize: 14,
    color: '#ff6600',
    fontWeight: '600',
  },
  selectBtn: {
    borderWidth: 1,
    borderColor: "#e0e0e0",
    borderRadius: 12,
    padding: 12,
    marginVertical: 8,
    backgroundColor: "#ffffff",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 3,
    elevation: 2,
  },
  imagePicker: {
    height: 200,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: "#ff6600",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginVertical: 12,
    backgroundColor: '#fff9f5',
  },
  imagePickerSmall: {
    height: 120,
    borderWidth: 2,
    borderStyle: 'dashed',
    borderColor: "#ffd9b3",
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    marginTop: 8,
    backgroundColor: '#ffffff',
  },
  addBtn: {
    backgroundColor: "#ff8533",
    padding: 12,
    borderRadius: 10,
    alignItems: "center",
    marginVertical: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  submitBtn: {
    backgroundColor: "#ff6600",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginTop: 20,
    marginBottom: 30,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.2,
    shadowRadius: 4,
    elevation: 4,
  },
  createBtn: {
    backgroundColor: "#ff8533",
    padding: 12,
    borderRadius: 10,
    alignItems: "center",
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  listItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderColor: "#f0f0f0",
    backgroundColor: '#ffffff',
  },
  closeBtn: {
    marginTop: 24,
    marginBottom: 12,
    backgroundColor: "#ff6600",
    padding: 14,
    borderRadius: 12,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.15,
    shadowRadius: 3,
    elevation: 3,
  },
  modalTitle: { 
    fontSize: 20, 
    fontWeight: "700", 
    marginBottom: 16,
    color: "#ff6600",
  },
  stepTitle: { 
    fontSize: 18,
    fontWeight: "600", 
    marginVertical: 12,
    color: "#ff6600",
  },
  stepRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  removeStepBtn: {
    width: 36,
    height: 36,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#ffecec',
    borderWidth: 1,
    borderColor: '#ffd6d6',
  },
  removeStepText: {
    color: '#d64545',
    fontWeight: '700',
    fontSize: 16,
  },
  // New styles for ingredients section
  card: {
    backgroundColor: '#ffffff',
    borderRadius: 12,
    padding: 16,
    marginVertical: 8,
    borderWidth: 1,
    borderColor: '#e0e0e0',
  },
  cardHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  cardTitle: {
    fontSize: 18,
    fontWeight: '600',
    color: '#333',
  },
  addButton: {
    backgroundColor: '#ff6600',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 8,
  },
  addButtonText: {
    color: '#ffffff',
    fontWeight: '600',
    fontSize: 14,
  },
  ingredientsList: {
    marginTop: 4,
  },
  ingredientRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 4,
  },
  ingredientText: {
    flex: 1,
    fontSize: 16,
    color: '#333',
    lineHeight: 24,
  },
  removeButton: {
    width: 24,
    height: 24,
    borderRadius: 12,
    backgroundColor: '#ffecec',
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: 8,
  },
  removeButtonText: {
    color: '#d64545',
    fontSize: 14,
    fontWeight: '600',
  },
  emptyText: {
    color: '#666',
    fontStyle: 'italic',
    paddingVertical: 8,
  },
});
