import { StyleSheet } from "react-native";
import { widthPercentageToDP as wp } from "react-native-responsive-screen";

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#FAFAFA",
  },
  header: {
    flexDirection: "row",
    alignItems: "center",
    padding: 12,
    borderBottomWidth: 1,
    borderColor: "#eee",
  },
  backBtn: { padding: 6 },
  headerBtn: { padding: 6 },
  image: {
    width: wp("95%"),
    height: wp("55%"),
    borderRadius: 16,
    margin: 10,
    alignSelf: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  infoRow: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginVertical: 12,
    backgroundColor: "#FFF",
    marginHorizontal: 12,
    paddingVertical: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  authorRow: {
    flexDirection: "row",
    alignItems: "center",
    marginHorizontal: 12,
    marginBottom: 12,
    backgroundColor: "#FFF",
    padding: 12,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  avatar: {
    width: 48,
    height: 48,
    borderRadius: 24,
    marginRight: 12,
    borderWidth: 2,
    borderColor: "#FF6B35",
  },
  author: {
    fontWeight: "bold",
    fontSize: 17,
    color: "#1A1A1A",
  },
  time: {
    color: "#666",
    fontSize: 13,
    marginTop: 2,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    margin: 12,
    marginTop: 16,
    color: "#1A1A1A",
    lineHeight: 32,
  },
  card: {
    backgroundColor: "#FFF",
    marginHorizontal: 12,
    marginBottom: 12,
    padding: 16,
    borderRadius: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  cardLarge: {
    backgroundColor: "#FFF",
    marginHorizontal: 12,
    padding: 20,
    borderRadius: 12,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.08,
    shadowRadius: 4,
    elevation: 2,
  },
  cardTitle: {
    fontWeight: "bold",
    fontSize: 18,
    color: "#1A1A1A",
  },
  cardDesc: {
    color: "#555",
    lineHeight: 22,
    fontSize: 15,
  },
  section: {
    fontWeight: "bold",
    fontSize: 18,
    color: "#1A1A1A",
  },
  videoCard: {
    alignItems: "center",
    padding: 16,
    backgroundColor: "#FFF4E6",
    margin: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "#FFE0B2",
  },
  commentSection: {
    marginTop: 16,
    borderTopWidth: 8,
    borderTopColor: '#F5F5F5',
    minHeight: 400,
  },
  infoButton: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: "#F8F9FA",
  },
  infoText: {
    fontSize: 15,
    color: '#333',
    fontWeight: "600",
  },
  commentButton: {
    backgroundColor: '#4A90E2',
    marginHorizontal: 16,
    marginTop: 16,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    shadowColor: "#4A90E2",
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 3,
  },
  commentButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFF',
  },
  reportButton: {
    backgroundColor: '#FFF',
    marginHorizontal: 16,
    marginTop: 12,
    marginBottom: 20,
    paddingVertical: 14,
    paddingHorizontal: 16,
    borderRadius: 12,
    alignItems: 'center',
    borderWidth: 1.5,
    borderColor: '#DC3545',
  },
  reportButtonText: {
    fontSize: 15,
    fontWeight: '700',
    color: '#DC3545',
  },
  tagContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginHorizontal: 12,
    marginBottom: 12,
    alignItems: "center",
  },
  tagGroup: {
    flexDirection: "row",
    flexWrap: "wrap",
    marginLeft: 8,
  },
  tagItem: {
    backgroundColor: "#EEF3FF",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    marginRight: 8,
    marginBottom: 8,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 1 },
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 1,
  },
  tagText: {
    fontSize: 13,
    color: "#3A5BA0",
    fontWeight: "600",
  },
  difficultyBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    alignSelf: 'flex-start',
    marginLeft: 8,
  },
  difficultyText: {
    fontWeight: 'bold',
    fontSize: 13,
  },

  ratingContainer: {
    marginTop: 16,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: '#EEEEEE',
  },
  ratingLabel: {
    fontSize: 17,
    fontWeight: '700',
    marginBottom: 12,
    color: '#1A1A1A',
  },
  starsContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  starButton: {
    padding: 4,
  },
  starIcon: {
    fontSize: 36,
  },
  ratingText: {
    marginTop: 10,
    fontSize: 14,
    color: '#666',
    fontStyle: 'italic',
  },
  averageRatingContainer: {
    marginBottom: 12,
    backgroundColor: "#FFF9E6",
    padding: 12,
    borderRadius: 10,
    borderLeftWidth: 4,
    borderLeftColor: "#FFD700",
  },
  averageRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  averageRatingText: {
    fontSize: 17,
    color: '#1A1A1A',
    fontWeight: '700',
  },
});

export default styles;
